version: '3.4'

services:
    catalogdb:
        image: mongo
    basketdb:
        image: redis

    mobilebazar.catalog.api:
        image: ${DOCKER_REGISTRY-}mobilebazarcatalogapi
        build:
          context: .
          dockerfile: src/Catalog/MobileBazar.Catalog.API/Dockerfile

    mobilebazar.basket.api:
        image: ${DOCKER_REGISTRY-}mobilebazarbasketapi
        build:
          context: .
          dockerfile: src/Basket/MobileBazar.Basket.API/Dockerfile

